### ISSUE TITLE
increase-inbound-liquidity  has (--max-fee 2000) correction to --fee-rate (per vbyte)

### ISSUE THREAD

**Issue by xraid** [niteshbalusu11/BOS-Commands-Document#1]
WRONG :
Example: bos increate-inbound-liquidity --with yourPeerPubkey --max-fee 2000 --dryrun

RIGHT :
Example: bos increate-inbound-liquidity --with yourPeerPubkey  --fee-rate (per vbyte) --dryrun

**Comment by niteshbalusu11** [comment]
> WRONG : Example: bos increate-inbound-liquidity --with yourPeerPubkey --max-fee 2000 --dryrun
> 
> RIGHT : Example: bos increate-inbound-liquidity --with yourPeerPubkey --fee-rate (per vbyte) --dryrun

Thanks for reporting. I’ll take a look and fix it if there is a mistake.

**Comment by niteshbalusu11** [comment]
`bos increase-inbound-liquidity` does not have a fee-rate flag. However, there was a spelling error in the example command and I fixed that.
I believe `LOOP` server controls the on-chain fee (sat/vByte) because they are doing the on-chain transaction.
